server:
  port: 8080
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          predicates:
            - Path=/products/
          uri: localhost:8081
        - id: order-service
          predicates:
            - Path=/orders/
          uri: localhost:8082
        - id: inventory-service
          predicates:
            - Path=/inventory/
          uri: localhost:8083


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
