# Use root/example as user/password credentials
version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"  # Map port 27017 on the host to port 27017 on the container
    volumes:
      - mongo-data:/data/db  # Use a named volume to persist MongoDB data

  mongo-express: #web gui
    image: mongo-express
    restart: always
    ports:
      - "27000:8081"  # Map port 27000 on the host to port 8081 on the container
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"

volumes:
  mongo-data: