
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri:  mongodb://root:example@localhost:27017/products?authSource=admin
server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
