
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri:  mongodb://root:example@localhost:27017/product-service?authSource=admin
  #  for load balancing
  cloud:
    loadbalancer:
      zone:
        enabled: true

server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
