version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#    ports:
#      - "9090:9090"
    network_mode: host
#    networks:
#      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
#    ports:
#      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    network_mode: host
#    networks:
#      - monitoring

volumes:
  grafana-data:

#networks:
#  monitoring:
#    driver: bridge
