version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: learning-microservices
      MYSQL_USER: imran
      MYSQL_PASSWORD: dev.imran
    ports:
      - "3300:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local